[CRITEO] Make conf "-default.xml" files compatibles with HDP2
It will solves error like :
  java.lang.NumberFormatException: For input string: "30s"

Once all the stack will be migrated to hadoop3. We will be able to
revert this change.

(cherry picked from commit b4ef7399ae1e02831f29376340b2d70564a3f503)